import{a as v,S,i as u}from"./assets/vendor-f736e62a.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(e){if(e.ep)return;e.ep=!0;const s=a(e);fetch(e.href,s)}})();//! У файлі pixabay-api.js зберігаються функції для HTTP-запитів.
const w="https://pixabay.com/api/",P="43217823-e472439c26018cf28ab0cff6b";async function h(r,t){const a=new URLSearchParams({key:P,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t});return(await v.get(`${w}?${a}`)).data}//! У файлі render-functions.js - функції для відображення елементів інтерфейсу.
function p(r){return r.map(({largeImageURL:t,webformatURL:a,tags:i,likes:e,views:s,comments:n,downloads:b})=>`<li class="li-js">
    <a href="${t}">
        <img src="${a}" alt="${i}" width="360" height="155"/>
    </a>
        <ul class="characteristics">
            <li>Likes<br> <span class="span">${e}</span></li>
            <li>Views<br> <span class="span">${s}</span></li>
            <li>Comments<br> <span class="span">${n}</span></li>
            <li>Downloads<br> <span class="span">${b}</span></li>
        </ul>
    </li>`).join("")}//! У файлі main.js знаходиться вся логіка роботи додатка.
const f=new S(".list a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250,overlayOpacity:.8}),q=document.querySelector(".search-form"),m=document.querySelector(".loader"),d=document.querySelector(".search-input"),c=document.querySelector("ul"),o=document.querySelector(".load-more-button");let l=1,y=15;async function M(r){if(r.preventDefault(),l=1,d.value.trim()!==""){c.innerHTML="",o.classList.add("load-more-hidden"),g();try{const t=await h(d.value.trim(),l);c.innerHTML="",c.insertAdjacentHTML("beforeend",p(t.hits)),f.refresh(),t.hits.length===0?(o.classList.add("load-more-hidden"),u.show({message:"Sorry, there are no images matching your search query. Please try again!",color:"red",position:"topRight"})):t.totalHits<=y?o.classList.add("load-more-hidden"):o.classList.remove("load-more-hidden"),L()}catch(t){alert(t)}}}q.addEventListener("submit",M);o.addEventListener("click",$);async function $(){l+=1,g(),o.disabled=!0;try{const r=await h(d.value.trim(),l);L(),c.insertAdjacentHTML("beforeend",p(r.hits)),f.refresh(),o.disabled=!1;const t=c.querySelector(".li-js").getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"});const a=Math.ceil(r.totalHits/y);l>=a&&(o.classList.add("load-more-hidden"),u.info({title:"",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(r){alert(r.message)}}function g(){m.classList.remove("none")}function L(){m.classList.add("none")}
//# sourceMappingURL=commonHelpers.js.map
