import{a as b,S as v,i as u}from"./assets/vendor-f736e62a.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();//! У файлі pixabay-api.js зберігаються функції для HTTP-запитів.
const S="https://pixabay.com/api/",w="43217823-e472439c26018cf28ab0cff6b";async function p(s,t){const o=new URLSearchParams({key:w,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t});return(await b.get(`${S}?${o}`)).data}//! У файлі render-functions.js - функції для відображення елементів інтерфейсу.
function h(s){return s.map(({largeImageURL:t,webformatURL:o,tags:n,likes:e,views:r,comments:i,downloads:L})=>`<li class="li-js">
    <a href="${t}">
        <img src="${o}" alt="${n}" width="360" height="155"/>
    </a>
        <ul class="characteristics">
            <li>Likes<br> <span class="span">${e}</span></li>
            <li>Views<br> <span class="span">${r}</span></li>
            <li>Comments<br> <span class="span">${i}</span></li>
            <li>Downloads<br> <span class="span">${L}</span></li>
        </ul>
    </li>`).join("")}//! У файлі main.js знаходиться вся логіка роботи додатка.
const f=new v(".list a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250,overlayOpacity:.8}),P=document.querySelector(".search-form"),m=document.querySelector(".loader"),d=document.querySelector(".search-input"),l=document.querySelector("ul"),a=document.querySelector(".load-more-button");let c=1,q=15;function $(s){s.preventDefault(),c=1,d.value.trim()!==""&&(y(),p(d.value.trim()).then(t=>{l.innerHTML="",l.insertAdjacentHTML("beforeend",h(t.hits)),f.refresh(),t.hits.length===0?(a.classList.add("load-more-hidden"),u.show({message:"Sorry, there are no images matching your search query. Please try again!",color:"red",position:"topRight"})):a.classList.remove("load-more-hidden")}).catch(t=>alert(t)).finally(()=>{g()}))}P.addEventListener("submit",$);a.addEventListener("click",M);async function M(){c+=1,y(),a.disabled=!0;try{const s=await p(d.value.trim(),c);g(),l.insertAdjacentHTML("beforeend",h(s.hits)),f.refresh(),a.disabled=!1;const t=l.querySelector(".li-js").getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"});const o=Math.ceil(s.totalHits/q);c>=o&&(a.classList.add("load-more-hidden"),u.info({title:"",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(s){alert(s.message)}}function y(){m.classList.remove("none")}function g(){m.classList.add("none")}
//# sourceMappingURL=commonHelpers.js.map
